# Generated by Django 3.0.3 on 2020-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('sources', models.ManyToManyField(blank=True, to='ecohub.Source')),
            ],
        ),
    ]
