# Generated by Django 3.0.3 on 2020-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0003_article_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='Short Abstract', max_length=511),
        ),
    ]
