# Generated by Django 3.0.3 on 2020-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0005_auto_20200313_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='short',
            field=models.CharField(default='source', max_length=67),
        ),
    ]
