# Generated by Django 3.0.3 on 2020-03-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0006_source_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
