# Generated by Django 3.0.3 on 2020-03-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0007_auto_20200317_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscategory',
            old_name='news_category',
            new_name='category_name',
        ),
    ]
