# Generated by Django 3.0.3 on 2020-03-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='author', max_length=127),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=127),
        ),
    ]
