# Generated by Django 3.0.3 on 2020-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0010_auto_20200326_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
