# Generated by Django 3.0.3 on 2020-04-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0012_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
