# Generated by Django 3.0.3 on 2020-04-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0013_auto_20200406_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
