# Generated by Django 3.0.3 on 2020-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0015_auto_20200406_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
            ],
        ),
    ]
