# Generated by Django 3.0.3 on 2020-04-11 17:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecohub', '0016_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(default=datetime.datetime(2020, 4, 11, 18, 5, 28, 529085), verbose_name='date sent')),
                ('message_subject', models.CharField(choices=[('more', 'More information'), ('collaboration', 'Collaboration offer'), ('join', 'Join Project'), ('invest', 'Make investment'), ('advertise', 'Advertisement'), ('other', 'Other business offer')], max_length=64)),
                ('message_text', models.TextField()),
                ('project_reference', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecohub.Project', verbose_name='Project')),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
