# Generated by Django 3.0.3 on 2020-04-12 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0017_auto_20200411_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 10, 28, 18, 528095), verbose_name='date sent'),
        ),
    ]
