# Generated by Django 3.0.3 on 2020-04-12 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0018_auto_20200412_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 15, 9, 48, 278246), verbose_name='date sent'),
        ),
    ]
