# Generated by Django 3.0.3 on 2020-04-12 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0021_auto_20200412_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 15, 27, 57, 528593), verbose_name='date sent'),
        ),
    ]
