# Generated by Django 3.0.3 on 2020-04-14 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0023_auto_20200412_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 6, 18, 41, 471925), verbose_name='date sent'),
        ),
    ]
