# Generated by Django 3.0.3 on 2020-04-14 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0024_auto_20200414_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='attachment',
            new_name='attachement',
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 6, 52, 0, 920031), verbose_name='date sent'),
        ),
    ]
