# Generated by Django 3.0.3 on 2020-04-15 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0025_auto_20200414_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='attachement',
            new_name='attachment',
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 6, 13, 49, 349879), verbose_name='date sent'),
        ),
    ]
