# Generated by Django 3.0.3 on 2020-04-16 04:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecohub', '0028_auto_20200415_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 5, 46, 1, 77428), verbose_name='date sent'),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated', models.DateTimeField(default=datetime.datetime(2020, 4, 16, 5, 46, 1, 78425), verbose_name='date sent')),
                ('amount', models.BigIntegerField()),
                ('contributor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('project_reference', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ecohub.Project', verbose_name='Project')),
            ],
        ),
    ]
