# Generated by Django 3.0.3 on 2020-04-17 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohub', '0029_auto_20200416_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_subject',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='fund',
            name='donated',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 5, 55, 19, 267101), verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 5, 55, 19, 267101), verbose_name='date sent'),
        ),
    ]
